-- SuperD: seed data for a deployer operating in Accra, Ghana - 10 zones
-- covering the greater Accra area, each with a starter list of named
-- locations. Purely optional reference data (see zone_locations.sql's
-- comment: these are for whoever's managing a zone, not something a
-- driver/vendor picks between directly) - a super admin can rename, add
-- to, or delete any of it afterwards from Console > Zones exactly like a
-- zone created by hand. No coordinates are seeded here (the Zones tab's
-- "add location" flow always pins one via the map, but a location doesn't
-- need one - see ZoneLocation.hasCoordinates), so a super admin can add
-- precise pins later for any of these worth mapping exactly.
--
-- Idempotent: safe to run again (e.g. on a fresh migration replay) without
-- creating duplicate zones or locations.

insert into public.zones (name) values
  ('Central Accra'),
  ('Airport-East Legon'),
  ('Osu-Cantonments-Labone'),
  ('Legon-Madina-North Accra'),
  ('Adenta-Aburi Corridor'),
  ('Teshie-Nungua-Spintex'),
  ('Tema-Kpone'),
  ('West Accra'),
  ('North-West Accra'),
  ('Kasoa-Outer West')
on conflict (name) do nothing;

insert into public.zone_locations (zone_id, name)
select z.id, loc.name
from (values
  ('Central Accra', 'Accra Central'),
  ('Central Accra', 'Adabraka'),
  ('Central Accra', 'Tudu'),
  ('Central Accra', 'Makola'),
  ('Central Accra', 'Rawlings Park'),
  ('Central Accra', 'Ridge'),
  ('Central Accra', 'North Ridge'),
  ('Central Accra', 'Ministries'),
  ('Central Accra', 'Victoriaborg'),
  ('Central Accra', 'Ringway'),
  ('Central Accra', 'Kwame Nkrumah Circle'),
  ('Central Accra', 'Asylum Down'),
  ('Central Accra', 'Odaw'),
  ('Central Accra', 'Kokomlemle'),
  ('Central Accra', 'High Street'),

  ('Airport-East Legon', 'Airport Residential'),
  ('Airport-East Legon', 'Airport City'),
  ('Airport-East Legon', 'East Legon'),
  ('Airport-East Legon', 'East Legon Hills'),
  ('Airport-East Legon', 'Shiashie'),
  ('Airport-East Legon', 'Dzorwulu'),
  ('Airport-East Legon', 'Roman Ridge'),
  ('Airport-East Legon', 'West Airport'),
  ('Airport-East Legon', 'American House'),
  ('Airport-East Legon', 'Bawaleshie'),
  ('Airport-East Legon', 'Okponglo'),
  ('Airport-East Legon', 'Mensah Wood'),
  ('Airport-East Legon', 'Trassaco'),
  ('Airport-East Legon', 'Trasacco Valley'),
  ('Airport-East Legon', 'Boundary Road'),

  ('Osu-Cantonments-Labone', 'Osu'),
  ('Osu-Cantonments-Labone', 'Cantonments'),
  ('Osu-Cantonments-Labone', 'Labone'),
  ('Osu-Cantonments-Labone', 'Ako Adjei'),
  ('Osu-Cantonments-Labone', 'Osu Oxford Street'),
  ('Osu-Cantonments-Labone', 'Osu Ako-Adjei'),
  ('Osu-Cantonments-Labone', 'Labone Junction'),
  ('Osu-Cantonments-Labone', 'Ministries Enclave'),
  ('Osu-Cantonments-Labone', 'Kanda'),
  ('Osu-Cantonments-Labone', 'Kanda Estate'),
  ('Osu-Cantonments-Labone', 'Golden Tulip area'),
  ('Osu-Cantonments-Labone', '37 Military Hospital area'),
  ('Osu-Cantonments-Labone', 'La'),
  ('Osu-Cantonments-Labone', 'La Paz Gardens'),
  ('Osu-Cantonments-Labone', 'Switchback'),

  ('Legon-Madina-North Accra', 'Legon'),
  ('Legon-Madina-North Accra', 'University of Ghana'),
  ('Legon-Madina-North Accra', 'Madina'),
  ('Legon-Madina-North Accra', 'Atomic'),
  ('Legon-Madina-North Accra', 'Haatso'),
  ('Legon-Madina-North Accra', 'Agbogba'),
  ('Legon-Madina-North Accra', 'North Legon'),
  ('Legon-Madina-North Accra', 'West Legon'),
  ('Legon-Madina-North Accra', 'Taifa'),
  ('Legon-Madina-North Accra', 'Dome'),
  ('Legon-Madina-North Accra', 'Kwabenya'),
  ('Legon-Madina-North Accra', 'Pantang'),
  ('Legon-Madina-North Accra', 'Oyarifa'),
  ('Legon-Madina-North Accra', 'Ashongman'),
  ('Legon-Madina-North Accra', 'Adenta-Frafraha'),

  ('Adenta-Aburi Corridor', 'Adenta'),
  ('Adenta-Aburi Corridor', 'Frafraha'),
  ('Adenta-Aburi Corridor', 'Ogbojo'),
  ('Adenta-Aburi Corridor', 'Lakeside'),
  ('Adenta-Aburi Corridor', 'Lakeside Estate'),
  ('Adenta-Aburi Corridor', 'Amrahia'),
  ('Adenta-Aburi Corridor', 'Oyibi'),
  ('Adenta-Aburi Corridor', 'Dodowa'),
  ('Adenta-Aburi Corridor', 'Danfa'),
  ('Adenta-Aburi Corridor', 'Ashaley Botwe'),
  ('Adenta-Aburi Corridor', 'Adenta Housing'),
  ('Adenta-Aburi Corridor', 'Pantang'),
  ('Adenta-Aburi Corridor', 'Ashiyie'),
  ('Adenta-Aburi Corridor', 'Zongo'),
  ('Adenta-Aburi Corridor', 'Aburi'),

  ('Teshie-Nungua-Spintex', 'Teshie'),
  ('Teshie-Nungua-Spintex', 'Nungua'),
  ('Teshie-Nungua-Spintex', 'Spintex'),
  ('Teshie-Nungua-Spintex', 'Baatsona'),
  ('Teshie-Nungua-Spintex', 'Sakumono'),
  ('Teshie-Nungua-Spintex', 'Klagon'),
  ('Teshie-Nungua-Spintex', 'Manet'),
  ('Teshie-Nungua-Spintex', 'Community 18'),
  ('Teshie-Nungua-Spintex', 'Lashibi'),
  ('Teshie-Nungua-Spintex', 'Coca-Cola Roundabout'),
  ('Teshie-Nungua-Spintex', 'Flowerpot'),
  ('Teshie-Nungua-Spintex', 'Nungua Estate'),
  ('Teshie-Nungua-Spintex', 'Teshie First Junction'),
  ('Teshie-Nungua-Spintex', 'Teshie Camp 2'),
  ('Teshie-Nungua-Spintex', 'Accra Mall area'),

  ('Tema-Kpone', 'Tema Community 1'),
  ('Tema-Kpone', 'Community 2'),
  ('Tema-Kpone', 'Community 3'),
  ('Tema-Kpone', 'Community 4'),
  ('Tema-Kpone', 'Community 5'),
  ('Tema-Kpone', 'Community 6'),
  ('Tema-Kpone', 'Community 7'),
  ('Tema-Kpone', 'Community 8'),
  ('Tema-Kpone', 'Community 9'),
  ('Tema-Kpone', 'Community 10'),
  ('Tema-Kpone', 'Community 11'),
  ('Tema-Kpone', 'Community 12'),
  ('Tema-Kpone', 'Community 18'),
  ('Tema-Kpone', 'Tema Harbour'),
  ('Tema-Kpone', 'Kpone'),

  ('West Accra', 'Kaneshie'),
  ('West Accra', 'Odorkor'),
  ('West Accra', 'Dansoman'),
  ('West Accra', 'Mamprobi'),
  ('West Accra', 'Chorkor'),
  ('West Accra', 'Korle Gonno'),
  ('West Accra', 'Korle Bu'),
  ('West Accra', 'Mataheko'),
  ('West Accra', 'Abossey Okai'),
  ('West Accra', 'Darkuman'),
  ('West Accra', 'Bubiashie'),
  ('West Accra', 'New Mamprobi'),
  ('West Accra', 'Sukura'),
  ('West Accra', 'Glefe'),
  ('West Accra', 'Laterbiokorshie'),

  ('North-West Accra', 'Lapaz'),
  ('North-West Accra', 'Abeka'),
  ('North-West Accra', 'Achimota'),
  ('North-West Accra', 'Awoshie'),
  ('North-West Accra', 'Akweteyman'),
  ('North-West Accra', 'Santa Maria'),
  ('North-West Accra', 'Sowutuom'),
  ('North-West Accra', 'Odorkor'),
  ('North-West Accra', 'Anyaa'),
  ('North-West Accra', 'Ablekuma'),
  ('North-West Accra', 'McCarthy Hill'),
  ('North-West Accra', 'Mallam'),
  ('North-West Accra', 'Kwashie Bu'),
  ('North-West Accra', 'New Fadama'),
  ('North-West Accra', 'Tesano'),

  ('Kasoa-Outer West', 'Kasoa'),
  ('Kasoa-Outer West', 'Opeikuma'),
  ('Kasoa-Outer West', 'Nyanyano'),
  ('Kasoa-Outer West', 'Buduburam'),
  ('Kasoa-Outer West', 'Awutu-Beraku'),
  ('Kasoa-Outer West', 'Gomoa Buduburam'),
  ('Kasoa-Outer West', 'Kasoa New Market'),
  ('Kasoa-Outer West', 'Kasoa CP'),
  ('Kasoa-Outer West', 'Iron City'),
  ('Kasoa-Outer West', 'Millennium City'),
  ('Kasoa-Outer West', 'Galilea'),
  ('Kasoa-Outer West', 'Kokrobite'),
  ('Kasoa-Outer West', 'Bortianor'),
  ('Kasoa-Outer West', 'Weija'),
  ('Kasoa-Outer West', 'West Hills')
) as loc(zone_name, name)
join public.zones z on z.name = loc.zone_name
where not exists (
  select 1 from public.zone_locations existing
  where existing.zone_id = z.id and existing.name = loc.name
);
